"""Generated optimizer tool contract."""

from __future__ import annotations

REQUIRED_ENTRYPOINT = "rank_candidates"

FORBIDDEN_TERMS: tuple[str, ...] = (
    "BOReferencePolicy",
    "MenuRestrictedBOReferencePolicy",
    "evaluation.bo_reference",
    "evaluation.bo_reference.policy",
    "evaluation.bo_reference_runner",
    "csebo_harness",
    "candidate_scores.csv",
    "candidate_scores",
    "oracle",
    "bo_rank",
    "bo_top_k",
    "global_rank",
    "full_pool_rank",
    "selected_full_pool_rank",
    "posthoc",
    "top percentile",
    "regret",
    "reference_acquisition_score",
    "reference_acquisition_value",
    "reference_predictive_mean",
    "reference_predictive_std",
    "bo_acquisition_score",
    "bo_predictive_mean",
    "bo_predictive_std",
    "oracle_rank",
    "hidden_y",
    "hidden_yield",
    "unobserved_y",
    "turnover",
    "raw_row_index",
    "source_path",
    "candidate_id_map.private",
    "display_to_internal_id",
    "private_id_map",
    "api_key",
    "Authorization",
    "Bearer",
)

REQUIRED_OUTPUT_SCHEMA = {
    "type": "list[dict]",
    "required_fields": ["candidate_id", "score", "rank"],
    "description": (
        "rank_candidates(observed_df, candidate_df, memory, strategy_state, "
        "tool_state) must return one row per remaining candidate, sorted or "
        "ranked so rank=1 is the selected candidate."
    ),
}

ALLOWED_IMPORTS: tuple[str, ...] = (
    "numpy",
    "pandas",
    "math",
    "statistics",
    "random",
    "collections",
    "itertools",
    "sklearn.linear_model",
    "sklearn.ensemble",
    "sklearn.neighbors",
    "sklearn.preprocessing",
    "sklearn.pipeline",
    "sklearn.impute",
)

ALLOWED_SKLEARN_SYMBOLS: dict[str, tuple[str, ...]] = {
    "sklearn.linear_model": ("Ridge",),
    "sklearn.ensemble": ("RandomForestRegressor",),
    "sklearn.neighbors": ("KNeighborsRegressor",),
    "sklearn.preprocessing": ("StandardScaler",),
    "sklearn.impute": ("SimpleImputer",),
    "sklearn.pipeline": ("Pipeline",),
}

TOOL_SYNTHESIS_SCHEMA_VERSION = "research_tool_full_pool_v1"
TOOL_SYNTHESIS_POLICY_NAME = "ResearchToolFullPoolPolicy"

FORBIDDEN_IMPORT_ROOTS: tuple[str, ...] = (
    "os",
    "sys",
    "subprocess",
    "pathlib",
    "requests",
    "urllib",
    "socket",
    "http",
    "shutil",
    "pickle",
    "joblib",
    "botorch",
    "ax",
    "skopt",
    "openai",
    "commonstack",
    "csebo_harness",
    "evaluation.bo_reference",
    "evaluation.bo_reference.policy",
    "evaluation.bo_reference_runner",
    "research_tool_agent_full_pool.research_retriever",
    "research_tool_agent_full_pool.research_card_collector",
    "research_tool_agent_full_pool.live_research_freeze",
    "research_tool_agent_full_pool.research_query_planner",
    "research_tool_agent_full_pool.research_dataset_profile",
)

FORBIDDEN_CALL_NAMES: tuple[str, ...] = (
    "open",
    "getattr",
    "setattr",
    "hasattr",
    "eval",
    "exec",
    "compile",
    "globals",
    "locals",
    "vars",
    "__import__",
)

FORBIDDEN_ATTRIBUTE_CALLS: tuple[str, ...] = (
    "read_csv",
    "read_excel",
    "read_feather",
    "read_fwf",
    "read_gbq",
    "read_hdf",
    "read_html",
    "read_json",
    "read_orc",
    "read_parquet",
    "read_pickle",
    "read_sas",
    "read_spss",
    "read_sql",
    "read_sql_query",
    "read_sql_table",
    "read_stata",
    "read_table",
    "read_xml",
    "from_csv",
    "from_dict",
    "from_file",
    "from_records",
    "frombuffer",
    "fromfile",
    "genfromtxt",
    "loadtxt",
    "to_csv",
    "to_excel",
    "to_feather",
    "to_gbq",
    "to_hdf",
    "to_html",
    "to_json",
    "to_latex",
    "to_markdown",
    "to_orc",
    "to_parquet",
    "to_pickle",
    "to_sql",
    "to_stata",
    "to_xml",
    "load",
    "loads",
    "save",
    "savez",
    "savetxt",
    "dump",
    "dumps",
    "getenv",
    "system",
    "popen",
)
